### ISSUE TITLE
[Request] "GM Only" Option + Respect Entity Permissions?

### ISSUE THREAD

**Issue by patrickburk1988** [NekroDarkmoon/bulk-tasks#1]
This module is a godsend! The only downside I've encountered so far is that players have access to the "Bulk Tasks" button, and when they click it they can see the names of all entities — regardless of player permissions. They can't actually *do* anything to entities that they don't have permissions for, but you still run the risk of them seeing entities with names like "Surprise Goblin Boss", "Bedroom Hidden Treasure", etc.

It would be ideal if we had the option to hide the button from players, and also some way to ensure that players can only see entities that they have permissions for.

**Comment by NekroDarkmoon** [comment]
Will deffo add that with the next release.
