### ISSUE TITLE
BUG - Does not display items with parenthesis "()" anywhere in name

### ISSUE THREAD

**Issue by djd007** [NekroDarkmoon/bulk-tasks#12]
When opening up the Bulk Tasks -> Items it is only showing items that do not have any parenthesis marks in the name.

https://imgur.com/vqVLMho.png

**Comment by NekroDarkmoon** [comment]
Interesting, I'll take a look at it around Monday. Are there any errors in the console by any chance?

**Comment by djd007** [comment]
Just a warning that looks unrelated:

`foundry.js:9834 The Document#_id property is deprecated in favor of Document#id or Document#data#_id. Support will be removed in 0.9.0`

**Comment by NekroDarkmoon** [comment]
It's weird. I can't seem to be able to replicate that behaviour.

**Comment by djd007** [comment]
OK the other reason I can think of is that all of these items were imported from Roll20 using kakaroto's R20 Converter: https://github.com/kakaroto/R20Converter

Is there anything I can do to assist figuring it out?  What kinds of things do you need to know about the item?

**Comment by NekroDarkmoon** [comment]
I'm trying to figure out what could be used to help debug this. But also I'm also rewriting the entire module to be easier to use at the moment and provide better automation.

**Comment by NekroDarkmoon** [comment]
Whenever bulk menu is opened an object of the entries is generated. 

![image](https://user-images.githubusercontent.com/49667684/145991516-bdaee4cb-c3c1-4478-b4a5-d6f23312dd43.png)

Can you check if the items are listed in there?

**Comment by djd007** [comment]
No, they are not populating there.  I made a test item (feature) and put it in a folder with a bunch of the items that are not being rendered, the test item did show up but nothing else from the folder.

I duplicated an item (feature) that is not being rendered - and the duplicate **did** get rendered.

I tried renaming an item (feature) that was not being rendered and tried editing the item and saving it.  It is still not being rendered.

**Comment by NekroDarkmoon** [comment]
Hmm, I can think of two issues.

1) For some reason it isn't listed in the respective directory.
You can find that by typing `game.items.directory.folders` and check if it exists there.

2) The permissions on those items are borked.
`game.items.getName('exactName').data.permission.default`

**Comment by djd007** [comment]
Sorry I wasn't able to figure it out and deleted the items manually - I'm going to close this as a one time problem probably permissions from exporting Roll20 to Foundry.

Thanks for your looking into it!
