### ISSUE TITLE
Bulk Tasks not working after Importing Music Playlists from Compendium [FVTT 9.249]

### ISSUE THREAD

**Issue by jocolamarco** [NekroDarkmoon/bulk-tasks#14]
When I click in "Bulk Tasks" I get this error.
This is only occurring after updating Foundry

![image](https://user-images.githubusercontent.com/45291719/152523631-bc38af9b-23d1-4ead-8d5d-81f124b14198.png)

**Comment by NekroDarkmoon** [comment]
Weird, I can't seem to replicate it, and nothing in the new update should have affected it.

**Comment by jocolamarco** [comment]
I just tried again, with only the Bulk Tasks module and it works, therefore it must be a conflict with another module.

I'll have to dig and find the culprit.

**Comment by jocolamarco** [comment]
Apologies for re-opening but, I was able to confirm the issue happens with just "Bulk Tasks" module enabled.

![image](https://user-images.githubusercontent.com/45291719/153244714-04b09796-90d0-4edd-95e7-0afb8e80e921.png)


```
foundry.js:316 TypeError: An error occurred while rendering BulkMenu 95: Cannot read properties of undefined (reading 'permission')
    at bulkMenu.js:268:16
```

https://user-images.githubusercontent.com/45291719/153245159-b0f33b4b-abdd-4fb5-ab0f-f25d5a4b7f49.mp4

**Comment by NekroDarkmoon** [comment]
It seems like there's a document that is kind of borked. Can you see if bulk tasks works in a new world with just a few items?

**Comment by jocolamarco** [comment]
Clean world with a few monsters, no issues...

Any idea how I can find which document has the issue?

**Comment by jocolamarco** [comment]
I was able to do some debugging and pinpoint the issue to a Playlist Folder. I have renamed this as it seems to not be related to PF2E system.

Here's how to replicate.

1. Install and enable a Music Module such as "Ivan Duch's Music Packs"
2. Navigate to Compendium > Playlist
3. Right-click the Music Playlist and select "Import All Content" with default options
4. After Import, a folder is created in the "Audio Playlists" tab
5. Verify that "Bulk Tasks" no longer works

**Comment by NekroDarkmoon** [comment]
Hmm, I see. Thank you for the diagnosis. I'll take a look at the module and see what I can do about it. If I'm correct the way they create those playlists is incorrect. I'll provide a mitigation in the module to just not render anything that has an incorrect format.

**Comment by NekroDarkmoon** [comment]
Should be fixed in the next update.
