### ISSUE TITLE
[Feature] Option to delete empty folders?

### ISSUE THREAD

**Issue by Doresain** [NekroDarkmoon/bulk-tasks#15]
Hey, great module!

I was just deleting a bunch of actors in a bunch of folders today, and after using Bulk Tasks to delete the actors I still had to go through and manually right click -> delete each now-empty folder, I might not necessarily want to delete empty folders after deleting their contents *every* time, but it would be awesome to have as an option if feasible for this sort of case.

Thanks man!

**Comment by NekroDarkmoon** [comment]
I'll try to add this in soon ish.
