### ISSUE TITLE
No longer working after system update

### ISSUE THREAD

**Issue by jocolamarco** [NekroDarkmoon/bulk-tasks#16]
![image](https://user-images.githubusercontent.com/45291719/164977874-406b2926-1209-474a-8071-3e978a3ecc91.png)

![image](https://user-images.githubusercontent.com/45291719/164977887-4f62f8cd-4078-42a0-82fb-d4af24c766dd.png)

**Comment by NekroDarkmoon** [comment]
Hmmm it seems as if there is an item or document that doesn't have the permissions set up properly.

**Comment by NekroDarkmoon** [comment]
Your issue might be related to #14

**Comment by NekroDarkmoon** [comment]
Should be fixed in the next update.
